### ISSUE TITLE
Setting starting color

### ISSUE THREAD

**Issue by mroelandts** [nlfmt/pyqt-colorpicker-widget#2]
It would be useful if you could set the starting color of the colorpicker.
I have done this by doing:
```python
# create class
color_picker = ColorPicker()
color_picker.setHex("39732e")  # starting value or value comming from settings
color_picker.hexChanged()

# connect signal
color_picker.colorChanged.connect(self._on_color_change)
```
But maybe a function would be nice? Or an argument to pass to the ColorPicker class?

**Comment by tomfln** [comment]
Fixed in 1.3: 43680d4f9b75a6c7cf12e691b1cceef011a552b2
You can now pass the initial color to the class when instancing it.
I also made the original setting functions "private" (they are now `_setRGB()` and so on) and you can use the public `setRGB()` functions to set the current color at any time.

Look at the README for more information
